name: Build Semgrep image
run-name: "[Image build] Ref:${{ github.ref_name }} Event:${{ github.event_name }}"

env:
  SEMGREP_VERSION: "1.144.0"  # Update this to change the version for scheduled builds

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
  schedule:
    # Build every Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  semgrep:
    name: Build Semgrep image
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest and tagged images
        if: (github.ref_name == 'main' && github.ref_type == 'branch') || github.event_name == 'schedule'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            SEMGREP_VERSION=${{ env.SEMGREP_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}/semgrep:latest
            ghcr.io/${{ github.repository }}/semgrep:${{ env.SEMGREP_VERSION }}
